/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 15 08:51:59 GMT 2021
 */

package webapp.def;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import webapp.def.ServiceDef;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ServiceDef_ESTest extends ServiceDef_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ServiceDef serviceDef0 = new ServiceDef();
  }
}
