/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 15 08:53:36 GMT 2021
 */

package webapp.framework;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import webapp.framework.AesCrypterDef;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AesCrypterDef_ESTest extends AesCrypterDef_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AesCrypterDef aesCrypterDef0 = new AesCrypterDef();
  }
}
