/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 15 08:55:12 GMT 2021
 */

package webapp.framework;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import webapp.framework.Controller;
import webapp.framework.SecureCookieManager;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SecureCookieManager_ESTest extends SecureCookieManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SecureCookieManager secureCookieManager0 = new SecureCookieManager((Controller) null);
      // Undeclared exception!
      try { 
        secureCookieManager0.addSecureCookie("*Dj>q$}'", "", 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("webapp.framework.SecureCookieManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SecureCookieManager secureCookieManager0 = new SecureCookieManager((Controller) null);
      // Undeclared exception!
      try { 
        secureCookieManager0.getSecureCookieValue("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("webapp.framework.SecureCookieManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SecureCookieManager secureCookieManager0 = new SecureCookieManager((Controller) null);
      // Undeclared exception!
      try { 
        secureCookieManager0.addSecureCookieAsEternal("", "loginMessage");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("webapp.framework.SecureCookieManager", e);
      }
  }
}
