apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhealthcareclinic0
  labels:
    app: myhealthcareclinic0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myhealthcareclinic0
  template:
    metadata:
      labels:
        app: myhealthcareclinic0
    spec:
      containers:
      - name: myhealthcareclinic0
        image: redis
        ports:
        - containerPort: 6379
          name: redis
     
---

apiVersion: v1
kind: Service
metadata:
  name: myhealthcareclinic0
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app: myhealthcareclinic0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhealthcareclinic
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  selector:
    matchLabels:
      app: myhealthcareclinic
  template:
    metadata:
      labels:
        app: myhealthcareclinic
    spec:
      containers:
      - name: myhealthcareclinic
        image: devsecopspoccontainer.azurecr.io/myhealthcareclinic:#{Build.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "myhealthcareclinic0"

---

apiVersion: v1
kind: Service
metadata:
  name: myhealthcareclinic
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: myhealthcareclinic
