apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myhealthcareclinic
  name: myhealthcareclinic
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myhealthcareclinic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myhealthcareclinic
    spec:
      containers:
      - image: devsecopspoccontainer.azurecr.io/myhealthcareclinic:#{Build.BuildId}#
        name: myhealthcareclinic
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 8080 
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: myhealthcareclinic
  labels:
    run: myhealthcareclinic
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: myhealthcareclinic
  type: LoadBalancer
